services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - $HOME/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    ports:
      - "8887:8880"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]