services:
  audify:
    build:
      context: .
      dockerfile: Dockerfile
    image: audify
    volumes:
      - ./data:/app/data
      - $HOME/Documents/books/:/app/input
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - ./audify:/app/audify
      - $HOME/.config:/root/.config
      - /home/linuxbrew/.linuxbrew:/home/linuxbrew/.linuxbrew
      - ./app.py:/app/app.py
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
