services:
  audify:
    build:
      context: .
      dockerfile: Dockerfile
    image: audify
    volumes:
      - ./:/app/
      - $HOME/Documents/books/:/app/input
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.config:/root/.config
      - /home/linuxbrew/.linuxbrew:/home/linuxbrew/.linuxbrew
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
